#!/usr/bin/env bash
#Bash (init) script 11-manage_my_process that manages manage_my_proces

PID_FILE="/var/run/my_process.pid"

start() {
    ./manage_my_process &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
    fi
    ./manage_my_process &
    echo $! > "$PID_FILE"
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
